### ISSUE TITLE
maxIter => maxIterations on README

### ISSUE THREAD

**Issue by valkheim** [scijs/newton-raphson-method#1]
Hi,

I think there's a tiny mistake on README :

```diff
- maxIter (default: 20): Maximum permitted iterations.
+ maxIterations (default: 20): Maximum permitted iterations.
```

Because of https://github.com/scijs/newton-raphson-method/blob/master/index.js#L18

**Comment by rreusser** [comment]
Sorry I didn't get this fixed sooner, but @dansgithubuser has fixed it. Thanks!
